require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  UseCache: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config/ru'

Style/Documentation:
 Enabled: false

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Layout/LineLength:
  Max: 80

Style/AsciiComments:
  Enabled: false